[template]
cargo_generate_version = ">=0.10.0"
ignore = [
    ".git",
    ".github",
    "README.md",
]

[placeholders.mcu]
type    = "string"
prompt  = "Which MCU to target?"
choices = ["esp32", "esp8266"]
default = "esp32"